INSERT INTO movies (id, title, director, year, rating, description,genre) VALUES
('The Shawshank Redemption', 'Frank Darabont', 1994, 9.3, 'Two imprisoned men bond over common decency.'),
('The Godfather', 'Francis Ford Coppola', 1972, 9.2, 'Patriarch of crime dynasty transfers control to son.'),
('The Dark Knight', 'Christopher Nolan', 2008, 9.0, 'Batman faces the Joker in a psychological battle.'),
('12 Angry Men', 'Sidney Lumet', 1957, 9.0, 'Jury member fights to prevent wrongful conviction.'),
('Schindler List', 'Steven Spielberg', 1993, 9.0, 'Oskar Schindler saves Jews from Nazi persecution.'),
('The Lord of the Rings: The Return of the King', 'Peter Jackson', 2003, 9.0, 'Gandalf and Aragorn battle Sauron’s army.'),
('Pulp Fiction', 'Quentin Tarantino', 1994, 8.9, 'Interwoven tales of violence and redemption unfold.'),
('The Good, the Bad and the Ugly', 'Sergio Leone', 1966, 8.8, 'Three men seek buried gold during the Civil War.'),
('Fight Club', 'David Fincher', 1999, 8.8, 'Insomniac forms underground fight club that evolves.'),
('Forrest Gump', 'Robert Zemeckis', 1994, 8.8, 'Life events unfold through an Alabama man’s perspective.'),
('Inception', 'Christopher Nolan', 2010, 8.8, 'Thief plants an idea through dream-sharing technology.'),
('The Matrix', 'Lana Wachowski, Lilly Wachowski', 1999, 8.7, 'Programmer discovers reality is a machine simulation.'),
('Goodfellas', 'Martin Scorsese', 1990, 8.7, 'Henry Hill’s life in the mob detailed.'),
('One Flew Over the Cuckoo Nest', 'Milos Forman', 1975, 8.7, 'Criminal challenges oppressive mental institution nurse.'),
('Seven Samurai', 'Akira Kurosawa', 1954, 8.6, 'Samurai protect village from bandit attacks.'),
('Se7en', 'David Fincher', 1995, 8.6, 'Detectives hunt serial killer using deadly sins.'),
('The Silence of the Lambs', 'Jonathan Demme', 1991, 8.6, 'FBI cadet seeks help from cannibal killer.'),
('City of God', 'Fernando Meirelles, Kátia Lund', 2002, 8.6, 'Kids’ lives diverge in Rio’s slums.'),
('Life Is Beautiful', 'Roberto Benigni', 1997, 8.6, 'Jewish librarian shields son from Holocaust horrors.'),
('It is a Wonderful Life', 'Frank Capra', 1946, 8.6, 'Angel shows man life without his existence.'),
('The Usual Suspects', 'Bryan Singer', 1995, 8.5, 'Survivor recounts events leading to violent showdown.'),
('Saving Private Ryan', 'Steven Spielberg', 1998, 8.5, 'Soldiers go behind enemy lines to rescue paratrooper.'),
('The Green Mile', 'Frank Darabont', 1999, 8.5, 'Death Row guards affected by a mysterious inmate.'),
('Interstellar', 'Christopher Nolan', 2014, 8.6, 'Explorers travel through wormhole to save humanity.'),
('Psycho', 'Alfred Hitchcock', 1960, 8.5, 'Secretary embezzles money and checks into remote motel.'),
('Léon: The Professional', 'Luc Besson', 1994, 8.5, 'Girl becomes protégé of professional assassin.'),
('Parasite', 'Bong Joon Ho', 2019, 8.5, 'Class discrimination threatens symbiotic family relationship.'),
('The Lion King', 'Roger Allers, Rob Minkoff', 1994, 8.5, 'Lion prince fights bitter uncle for throne.'),
('Gladiator', 'Ridley Scott', 2000, 8.5, 'Roman General seeks vengeance against corrupt emperor.'),
('American History X', 'Tony Kaye', 1998, 8.5, 'Ex-skinhead tries to prevent brother’s path.'),
('The Departed', 'Martin Scorsese', 2006, 8.5, 'Undercover cop and mole seek to expose each other.'),
('The Prestige', 'Christopher Nolan', 2006, 8.5, 'Two magicians compete to create ultimate illusion.'),
('Whiplash', 'Damien Chazelle', 2014, 8.5, 'Drummer’s dreams are mentored by ruthless instructor.'),
('The Intouchables', 'Olivier Nakache, Éric Toledano', 2011, 8.5, 'Quadriplegic hires caregiver from projects.'),
('Modern Times', 'Charles Chaplin', 1936, 8.5, 'Tramp struggles to survive in industrial society.'),
('Once Upon a Time in the West', 'Sergio Leone', 1968, 8.5, 'Stranger and desperado protect widow from assassin.'),
('Hara-Kiri', 'Masaki Kobayashi', 1962, 8.6, 'Ronin’s past challenges feudal lord’s integrity.'),
('Alien', 'Ridley Scott', 1979, 8.4, 'Crew encounters mysterious life form on ship.'),
('Apocalypse Now', 'Francis Ford Coppola', 1979, 8.4, 'Officer tasked with assassinating renegade Special Forces Colonel.'),
('Memento', 'Christopher Nolan', 2000, 8.4, 'Man with memory loss tracks wife’s murderer.'),
('The Great Dictator', 'Charles Chaplin', 1940, 8.4, 'Jewish barber fights dictator’s oppressive regime.'),
('The Lives of Others', 'Florian Henckel von Donnersmarck', 2006, 8.4, 'Secret police agent becomes absorbed in surveillance.'),
('Django Unchained', 'Quentin Tarantino', 2012, 8.4, 'Freed slave seeks to rescue his wife.'),
('The Shining', 'Stanley Kubrick', 1980, 8.4, 'Family encounters sinister presence in isolated hotel.'),
('Paths of Glory', 'Stanley Kubrick', 1957, 8.4, 'Commanding officer defends soldiers accused of cowardice.'),
('WALL·E', 'Andrew Stanton', 2008, 8.4, 'Garbage collecting robot cleans up abandoned Earth.'),
('The Pianist', 'Roman Polanski', 2002, 8.5, 'Jewish musician survives destruction of Warsaw ghetto.'),
('Avengers: Infinity War', 'Anthony Russo, Joe Russo', 2018, 8.4, 'Avengers must sacrifice all to defeat Thanos.'),
('Joker', 'Todd Phillips', 2019, 8.4, 'Comedian turns into the Joker amidst societal neglect.'),
('Avengers: Endgame', 'Anthony Russo, Joe Russo', 2019, 8.4, 'Avengers assemble to reverse Thanos’s actions.'),
('Spider-Man: Into the Spider-Verse', 'Bob Persichetti, Peter Ramsey, Rodney Rothman', 2018, 8.4, 'Teen Spider-Man teams with spider-powered individuals.'),
('Your Name', 'Makoto Shinkai', 2016, 8.4, 'Strangers connected through body-swapping phenomenon.'),
('Capernaum', 'Nadine Labaki', 2018, 8.4, '12-year-old sues his parents for neglect.'),
('The Hunt', 'Thomas Vinterberg', 2012, 8.4, 'Teacher’s life ruined by false accusation.'),
('The Kid', 'Charles Chaplin', 1921, 8.4, 'Tramp raises orphaned child in comedic adventures.'),
('The Wizard of Oz', 'Victor Fleming', 1939, 8.4, 'Girl travels to magical land to meet wizard.'),
('Inception', 'Christopher Nolan', 2010, 8.8, 'Thief plants an idea through dream-sharing technology.'),
('The Conjuring', 'James Wan', 2013, 8.4, 'Paranormal investigators help family with sinister haunting.'),
('Inside Out', 'Pete Docter, Ronnie del Carmen', 2015, 8.4, 'Emotions navigate preteen’s challenges.'),
('A Beautiful Mind', 'Ron Howard', 2001, 8.4, 'Mathematician’s genius and struggles with mental illness.'),
('The Wolf of Wall Street', 'Martin Scorsese', 2013, 8.4, 'Stockbroker’s rise and fall due to greed and excess.'),
('The Secret Life of Walter Mitty', 'Ben Stiller', 2013, 8.4, 'Office worker escapes mundane life through vivid fantasies.'),
('The Imitation Game', 'Morten Tyldum', 2014, 8.4, 'Alan Turing’s code-breaking efforts during WWII.'),
('Gone Girl', 'David Fincher', 2014, 8.4, 'Woman’s mysterious disappearance causes media frenzy.'),
('Zodiac', 'David Fincher', 2007, 8.4, 'Journalists and detectives track Zodiac Killer in San Francisco.'),
('The Texas Chain Saw Massacre', 'Tobe Hooper', 1974, 8.4, 'Group of friends encounters cannibalistic family.'),
('The Great Beauty', 'Paolo Sorrentino', 2013, 8.4, 'Writer reflects on his life and the Rome he knows.'),
('The Hunt for Red October', 'John McTiernan', 1990, 8.4, 'Submarine captain defect attempts during Cold War.'),
('The Revenant', 'Alejandro G. Iñárritu', 2015, 8.4, 'Frontiersman seeks vengeance after being left for dead.'),
('The Witch', 'Robert Eggers', 2015, 8.4, 'Family’s faith is tested in 1630s New England.'),
('The Exorcist', 'William Friedkin', 1973, 8.4, 'Priests battle to save girl from demonic possession.'),
('Hereditary', 'Ari Aster', 2018, 8.4, 'Family confronts terrifying legacy of ancestors.'),
('The Others', 'Alejandro Amenábar', 2001, 8.4, 'Mother and children live in haunted mansion.'),
('The Babadook', 'Jennifer Kent', 2014, 8.4, 'Mother and son face haunting presence in their home.'),
('The Ring', 'Gore Verbinski', 2002, 8.4, 'Journalist investigates mysterious videotape with deadly curse.'),
('Annihilation', 'Alex Garland', 2018, 8.4, 'Scientists explore mysterious zone where reality is altered.'),
('Arrival', 'Denis Villeneuve', 2016, 8.4, 'Linguist deciphers alien language to avert global conflict.'),
('Ex Machina', 'Alex Garland', 2014, 8.4, 'Programmer evaluates AI’s consciousness and behavior.'),
('Blade Runner 2049', 'Denis Villeneuve', 2017, 8.4, 'New Blade Runner discovers secrets about the past.'),
('The Social Network', 'David Fincher', 2010, 8.4, 'The rise and fall of Facebook’s creator.'),
('The Truman Show', 'Peter Weir', 1998, 8.4, 'Man discovers his entire life is a TV show.'),
('The Big Lebowski', 'Joel Coen, Ethan Coen', 1998, 8.4, 'The Dude gets involved in a complex kidnapping case.'),
('A Clockwork Orange', 'Stanley Kubrick', 1971, 8.4, 'Teen delinquent undergoes controversial aversion therapy.'),
('The Breakfast Club', 'John Hughes', 1985, 8.4, 'High school students from different cliques bond during detention.'),
('The Princess Bride', 'Rob Reiner', 1987, 8.4, 'Fairy tale adventure filled with romance and comedy.'),
('Monty Python and the Holy Grail', 'Terry Gilliam, Terry Jones', 1975, 8.4, 'Comedy retelling of Arthurian legend.'),
('The Grandmaster', 'Wong Kar Wai', 2013, 8.4, 'Biographical martial arts film about Ip Man.'),
('Yojimbo', 'Akira Kurosawa', 1961, 8.4, 'Ronin helps two rival gangs in a small town.'),
('The Seventh Seal', 'Ingmar Bergman', 1957, 8.4, 'Knight challenges Death to a chess game during the Black Death.'),
('Sunset Boulevard', 'Billy Wilder', 1950, 8.4, 'Screenwriter’s life is changed by a faded starlet.'),
('The Deer Hunter', 'Michael Cimino', 1978, 8.4, 'Vietnam War’s impact on small-town friends.'),
('The Lion in Winter', 'Anthony Harvey', 1968, 8.4, 'Political maneuvering within the English royal family.'),
('The Bridge on the River Kwai', 'David Lean', 1957, 8.4, 'British POWs build bridge for Japanese forces in WWII.'),
('Lawrence of Arabia', 'David Lean', 1962, 8.4, 'British officer leads Arab revolt against Ottoman Empire.'),
('The Man Who Would Be King', 'John Huston', 1975, 8.4, 'Two British adventurers become kings of a remote tribe.'),
('Gandhi', 'Richard Attenborough', 1982, 8.4, 'Biopic of Mahatma Gandhi’s struggle for Indian independence.'),
('The Mission', 'Roland Joffé', 1986, 8.4, 'Jesuit priests defend South American natives from Portuguese slave traders.'),
('The Last Emperor', 'Bernardo Bertolucci', 1987, 8.4, 'Chinese Emperor’s life from childhood to exile.'),
('The Color Purple', 'Steven Spielberg', 1985, 8.4, 'African-American woman’s struggle for freedom in the early 20th century.'),
('The Pianist', 'Roman Polanski', 2002, 8.4, 'Jewish pianist’s struggle to survive during WWII.'),
('The English Patient', 'Anthony Minghella', 1996, 8.4, 'Wounded WWII soldier’s past is revealed through flashbacks.'),
('The 400 Blows', 'François Truffaut', 1959, 8.4, 'Young boy’s troubled childhood in Paris.'),
('The Battle of Algiers', 'Gillo Pontecorvo', 1966, 8.4, 'Algerian war for independence against French colonial forces.'),
('The Umbrellas of Cherbourg', 'Jacques Demy', 1964, 8.4, 'Romance told through a musical set in a French seaside town.'),
('The Wages of Fear', 'Henri-Georges Clouzot', 1953, 8.4, 'Four men transport explosives across treacherous terrain.'),
('The Third Man', 'Carol Reed', 1949, 8.4, 'Detective investigates the death of his friend in post-war Vienna.'),
('The 39 Steps', 'Alfred Hitchcock', 1935, 8.4, 'Man on the run from spies after being mistaken for a secret agent.'),
('The Good Place', 'Michael Schur', 2016, 8.0, 'Woman mistakenly sent to heaven tries to become a better person.'),
('The Perks of Being a Wallflower', 'Stephen Chbosky', 2012, 8.0, 'Introverted teen finds friendship and acceptance in high school.'),
('The Grand Seduction', 'Don McKellar', 2013, 8.0, 'Small town tries to lure a doctor to stay by faking a thriving community.'),
('The Lovely Bones', 'Peter Jackson', 2009, 8.0, 'Young girl watches over her family and murderer after being killed.'),
('The King’s Speech', 'Tom Hooper', 2010, 8.0, 'King George VI works to overcome his stammer with the help of a speech therapist.'),
('The Green Mile', 'Frank Darabont', 1999, 8.0, 'Death row officer forms a bond with a prisoner with a mysterious gift.'),
('The Book Thief', 'Brian Percival', 2013, 8.0, 'Young girl finds solace in stealing books during WWII in Nazi Germany.'),
('The Danish Girl', 'Tom Hooper', 2015, 8.0, 'The story of Lili Elbe, one of the first known recipients of sex reassignment surgery.'),
('The Secret Life of Pets', 'Chris Renaud', 2016, 8.0, 'What pets do when their owners are away.'),
('The Maze Runner', 'Wes Ball', 2014, 8.0, 'Teens trapped in a maze must find their way out while facing deadly challenges.'),
('The Curious Case of Benjamin Button', 'David Fincher', 2008, 8.0, 'A man ages backward, experiencing life in reverse.'),
('The Hateful Eight', 'Quentin Tarantino', 2015, 8.0, 'Eight strangers take refuge from a blizzard in a stagecoach lodge.'),
('The Fault in Our Stars', 'Josh Boone', 2014, 8.0, 'Teenagers with cancer meet at a support group and fall in love.'),
('The Social Network', 'David Fincher', 2010, 8.0, 'The story of Facebook’s founding and the ensuing legal battles.'),
('The Martian', 'Ridley Scott', 2015, 8.0, 'Astronaut stranded on Mars struggles to survive and return home.'),
('The Pursuit of Happyness', 'Gabriele Muccino', 2006, 8.0, 'Single father overcomes adversity to pursue his dream of becoming a stockbroker.'),
('The Help', 'Tate Taylor', 2011, 8.0, 'Young writer interviews African-American maids in the 1960s South.'),
('The Blind Side', 'John Lee Hancock', 2009, 8.0, 'Story of Michael Oher, a homeless teen who becomes a football star.'),
('The Devil Wears Prada', 'David Frankel', 2006, 8.0, 'Young woman navigates the demanding world of high fashion under a ruthless boss.'),
('The Vow', 'Michael Sucsy', 2012, 8.0, 'A man works to rekindle his relationship with his wife after she loses her memory.'),
('The Conjuring', 'James Wan', 2013, 8.0, 'Paranormal investigators help a family terrorized by a dark presence in their farmhouse.'),
('The Shining', 'Stanley Kubrick', 1980, 8.0, 'Family caretaker of a secluded hotel slowly descends into madness.'),
('The Walking Dead', 'Frank Darabont', 2010, 8.0, 'Group of survivors navigate a post-apocalyptic world overrun by zombies.'),
('The Hobbit: An Unexpected Journey', 'Peter Jackson', 2012, 8.0, 'Hobbit embarks on a quest to reclaim a lost kingdom.'),
('The Hunger Games', 'Gary Ross', 2012, 8.0, 'Teenagers fight to the death in a dystopian future society.'),
('The Boy in the Striped Pajamas', 'Mark Herman', 2008, 8.0, 'A young boy befriends a Jewish boy in a concentration camp.'),
('The Da Vinci Code', 'Ron Howard', 2006, 8.0, 'A symbologist uncovers a conspiracy while investigating a murder at the Louvre.'),
('The Notebook', 'Nick Cassavetes', 2004, 8.0, 'A love story spanning decades between a poor young man and a wealthy young woman.'),
('The Aviator', 'Martin Scorsese', 2004, 8.0, 'Biopic of Howard Hughes, focusing on his early career and aviation.'),
('The Descendants', 'Alexander Payne', 2011, 8.0, 'Hawaiian land baron tries to reconnect with his daughters after his wife’s accident.'),
('The Bourne Identity', 'Doug Liman', 2002, 8.0, 'Amnesiac assassin tries to piece together his past while evading pursuers.'),
('The Conjuring 2', 'James Wan', 2016, 8.0, 'Paranormal investigators help a family haunted by a demonic nun.'),
('The Hangover', 'Todd Phillips', 2009, 8.0, 'Three friends search for their missing friend after a wild bachelor party in Las Vegas.'),
('The Secret Life of Walter Mitty', 'Ben Stiller', 2013, 8.0, 'Daydreamer embarks on a global adventure to find a missing photo.'),
('The Accountant', 'Gavin O’Connor', 2016, 8.0, 'Autistic accountant with lethal skills uncovers a conspiracy.'),
('The Theory of Everything', 'James Marsh', 2014, 8.0, 'Biopic of Stephen Hawking’s life, focusing on his relationship with his first wife.'),
('The Big Short', 'Adam McKay', 2015, 8.0, 'Story of the financial crisis of 2007-2008 through the eyes of investors who bet against the housing market.'),
('The Sixth Sense', 'M. Night Shyamalan', 1999, 8.0, 'Child psychologist treats a young boy who claims to see dead people.'),
('The Intouchables', 'Olivier Nakache', 2011, 8.0, 'A quadriplegic aristocrat hires a young man from the projects to be his caregiver.'),
('The Girl with the Dragon Tattoo', 'David Fincher', 2011, 8.0, 'Journalist and hacker investigate a wealthy family’s dark secrets.'),
('The Dark Knight','Christopher Nolan',2008,8.0,'Batman faces off against the Joker, a criminal mastermind wreaking havoc on Gotham City.','Action');





