INSERT INTO movies (id, title, director, year, rating, description) VALUES
('The Shawshank Redemption', 'Frank Darabont', 1994, 9.3, 'Two imprisoned men bond over common decency.'),
('The Godfather', 'Francis Ford Coppola', 1972, 9.2, 'Patriarch of crime dynasty transfers control to son.'),
('The Dark Knight', 'Christopher Nolan', 2008, 9.0, 'Batman faces the Joker in a psychological battle.'),
('12 Angry Men', 'Sidney Lumet', 1957, 9.0, 'Jury member fights to prevent wrongful conviction.'),
('Schindler''s List', 'Steven Spielberg', 1993, 9.0, 'Oskar Schindler saves Jews from Nazi persecution.'),
('The Lord of the Rings: The Return of the King', 'Peter Jackson', 2003, 9.0, 'Gandalf and Aragorn battle Sauron’s army.'),
('Pulp Fiction', 'Quentin Tarantino', 1994, 8.9, 'Interwoven tales of violence and redemption unfold.'),
('The Good, the Bad and the Ugly', 'Sergio Leone', 1966, 8.8, 'Three men seek buried gold during the Civil War.'),
('Fight Club', 'David Fincher', 1999, 8.8, 'Insomniac forms underground fight club that evolves.'),
('Forrest Gump', 'Robert Zemeckis', 1994, 8.8, 'Life events unfold through an Alabama man’s perspective.'),
('Inception', 'Christopher Nolan', 2010, 8.8, 'Thief plants an idea through dream-sharing technology.'),
('The Matrix', 'Lana Wachowski, Lilly Wachowski', 1999, 8.7, 'Programmer discovers reality is a machine simulation.'),
('Goodfellas', 'Martin Scorsese', 1990, 8.7, 'Henry Hill’s life in the mob detailed.'),
('One Flew Over the Cuckoo''s Nest', 'Milos Forman', 1975, 8.7, 'Criminal challenges oppressive mental institution nurse.'),
('Seven Samurai', 'Akira Kurosawa', 1954, 8.6, 'Samurai protect village from bandit attacks.'),
('Se7en', 'David Fincher', 1995, 8.6, 'Detectives hunt serial killer using deadly sins.'),
('The Silence of the Lambs', 'Jonathan Demme', 1991, 8.6, 'FBI cadet seeks help from cannibal killer.'),
('City of God', 'Fernando Meirelles, Kátia Lund', 2002, 8.6, 'Kids’ lives diverge in Rio’s slums.'),
('Life Is Beautiful', 'Roberto Benigni', 1997, 8.6, 'Jewish librarian shields son from Holocaust horrors.'),
('It''s a Wonderful Life', 'Frank Capra', 1946, 8.6, 'Angel shows man life without his existence.'),
('The Usual Suspects', 'Bryan Singer', 1995, 8.5, 'Survivor recounts events leading to violent showdown.'),
('Saving Private Ryan', 'Steven Spielberg', 1998, 8.5, 'Soldiers go behind enemy lines to rescue paratrooper.'),
('The Green Mile', 'Frank Darabont', 1999, 8.5, 'Death Row guards affected by a mysterious inmate.'),
('Interstellar', 'Christopher Nolan', 2014, 8.6, 'Explorers travel through wormhole to save humanity.'),
('Psycho', 'Alfred Hitchcock', 1960, 8.5, 'Secretary embezzles money and checks into remote motel.'),
('Léon: The Professional', 'Luc Besson', 1994, 8.5, 'Girl becomes protégé of professional assassin.'),
('Parasite', 'Bong Joon Ho', 2019, 8.5, 'Class discrimination threatens symbiotic family relationship.'),
('The Lion King', 'Roger Allers, Rob Minkoff', 1994, 8.5, 'Lion prince fights bitter uncle for throne.'),
('Gladiator', 'Ridley Scott', 2000, 8.5, 'Roman General seeks vengeance against corrupt emperor.'),
('American History X', 'Tony Kaye', 1998, 8.5, 'Ex-skinhead tries to prevent brother’s path.'),
('The Departed', 'Martin Scorsese', 2006, 8.5, 'Undercover cop and mole seek to expose each other.'),
('The Prestige', 'Christopher Nolan', 2006, 8.5, 'Two magicians compete to create ultimate illusion.'),
('Whiplash', 'Damien Chazelle', 2014, 8.5, 'Drummer’s dreams are mentored by ruthless instructor.'),
('The Intouchables', 'Olivier Nakache, Éric Toledano', 2011, 8.5, 'Quadriplegic hires caregiver from projects.'),
('Modern Times', 'Charles Chaplin', 1936, 8.5, 'Tramp struggles to survive in industrial society.'),
('Once Upon a Time in the West', 'Sergio Leone', 1968, 8.5, 'Stranger and desperado protect widow from assassin.'),
('Hara-Kiri', 'Masaki Kobayashi', 1962, 8.6, 'Ronin’s past challenges feudal lord’s integrity.'),
('Alien', 'Ridley Scott', 1979, 8.4, 'Crew encounters mysterious life form on ship.'),
('Apocalypse Now', 'Francis Ford Coppola', 1979, 8.4, 'Officer tasked with assassinating renegade Special Forces Colonel.'),
('Memento', 'Christopher Nolan', 2000, 8.4, 'Man with memory loss tracks wife’s murderer.'),
('The Great Dictator', 'Charles Chaplin', 1940, 8.4, 'Jewish barber fights dictator’s oppressive regime.'),
('The Lives of Others', 'Florian Henckel von Donnersmarck', 2006, 8.4, 'Secret police agent becomes absorbed in surveillance.'),
('Django Unchained', 'Quentin Tarantino', 2012, 8.4, 'Freed slave seeks to rescue his wife.'),
('The Shining', 'Stanley Kubrick', 1980, 8.4, 'Family encounters sinister presence in isolated hotel.'),
('Paths of Glory', 'Stanley Kubrick', 1957, 8.4, 'Commanding officer defends soldiers accused of cowardice.'),
('WALL·E', 'Andrew Stanton', 2008, 8.4, 'Garbage collecting robot cleans up abandoned Earth.'),
('The Pianist', 'Roman Polanski', 2002, 8.5, 'Jewish musician survives destruction of Warsaw ghetto.'),
('Avengers: Infinity War', 'Anthony Russo, Joe Russo', 2018, 8.4, 'Avengers must sacrifice all to defeat Thanos.'),
('Joker', 'Todd Phillips', 2019, 8.4, 'Comedian turns into the Joker amidst societal neglect.'),
('Avengers: Endgame', 'Anthony Russo, Joe Russo', 2019, 8.4, 'Avengers assemble to reverse Thanos’s actions.'),
( 'Spider-Man: Into the Spider-Verse', 'Bob Persichetti, Peter Ramsey, Rodney Rothman', 2018, 8.4, 'Teen Spider-Man teams with spider-powered individuals.'),
('Your Name', 'Makoto Shinkai', 2016, 8.4, 'Strangers connected in bizarre way attempt to meet.'),
('Coco', 'Lee Unkrich, Adrian Molina', 2017, 8.4, 'Musician enters Land of the Dead to find ancestor.'),
('Capernaum', 'Nadine Labaki', 2018, 8.4, 'Boy sues parents for neglect during imprisonment.'),
('3 Idiots', 'Rajkumar Hirani', 2009, 8.4, 'Friends revisit college days and memories of inspiration.'),
('Star Wars: Episode IV - A New Hope', 'George Lucas', 1977, 8.6, 'Luke Skywalker fights Empire to rescue Princess Leia.'),
('Reservoir Dogs', 'Quentin Tarantino', 1992, 8.3, 'Jewelry heist goes wrong; suspects a police informant.'),
('Inglourious Basterds', 'Quentin Tarantino', 2009, 8.3, 'Plan to assassinate Nazi leaders coincides with theatre owner’s plan.'),
('2001: A Space Odyssey', 'Stanley Kubrick', 1968, 8.3, 'Artifact discovery leads to quest with supercomputer HAL.'),
('Eternal Sunshine of the Spotless Mind', 'Michel Gondry', 2004, 8.3, 'Couple erases each other from memories after breakup.'),
('Requiem for a Dream', 'Darren Aronofsky', 2000, 8.3, 'Four people’s drug-induced utopias shattered by addiction.'),
('Toy Story', 'John Lasseter', 1995, 8.3, 'Cowboy doll threatened by new toy in the house.'),
('The Grand Budapest Hotel', 'Wes Anderson', 2014, 8.2, 'Concierge and protégé investigate a stolen painting.'),
('Moonlight', 'Barry Jenkins', 2016, 8.2, 'A young African-American grapples with identity and family.'),
('The Shape of Water', 'Guillermo del Toro', 2017, 8.0, 'Mute woman falls in love with amphibious creature.'),
('Mad Max: Fury Road', 'George Miller', 2015, 8.1, 'Max teams with Furiosa to escape tyrannical leader.'),
('Her', 'Spike Jonze', 2013, 8.0, 'Man falls in love with his operating system.'),
('The Revenant', 'Alejandro G. Iñárritu', 2015, 8.0, 'Frontiersman seeks revenge after being left for dead.'),
('The Witch', 'Robert Eggers', 2015, 8.0, 'Family encounters sinister forces in 1630s New England.'),
('The Florida Project', 'Sean Baker', 2017, 8.0, 'Young girl’s summer adventures near Disney World.'),
('Jumanji: Welcome to the Jungle', 'Jake Kasdan', 2017, 8.0, 'Teens are transported into a dangerous video game.'),
('The Babadook', 'Jennifer Kent', 2014, 8.0, 'Mother and son deal with a sinister book.'),
('Gone Girl', 'David Fincher', 2014, 8.0, 'A man becomes the prime suspect in his wife’s disappearance.'),
('The Hunt', 'Thomas Vinterberg', 2012, 8.0, 'Teacher’s life unravels after false child molestation accusation.'),
('Arrival', 'Denis Villeneuve', 2016, 8.0, 'Linguist communicates with aliens to prevent global conflict.'),
('Lock, Stock and Two Smoking Barrels', 'Guy Ritchie', 1998, 8.0, 'Four friends’ heist goes awry with unexpected twists.'),
('The Secret in Their Eyes', 'Juan José Campanella', 2009, 8.0, 'Retired legal counselor revisits unsolved case of rape.'),
('The Others', 'Alejandro Amenábar', 2001, 8.0, 'Mother suspects supernatural forces in her isolated house.'),
('The Imitation Game', 'Morten Tyldum', 2014, 8.0, 'Alan Turing decrypts Nazi messages during World War II.'),
('The Lion in Winter', 'Anthony Harvey', 1968, 8.0, 'Medieval drama of King Henry II’s turbulent family.'),
('The Man Who Wasn’t There', 'Joel Coen', 2001, 8.0, 'Barber gets involved in a blackmail scheme.'),
('Ratatouille', 'Brad Bird', 2007, 8.0, 'Rat becomes a chef in a Paris restaurant.'),
('The Cabin in the Woods', 'Drew Goddard', 2011, 8.0, 'Teens discover a sinister truth about their cabin.'),
('Kubo and the Two Strings', 'Travis Knight', 2016, 8.0, 'Boy with magical powers embarks on a quest.'),
('Sing Street', 'John Carney', 2016, 8.0, 'Teen forms a band to impress a girl.'),
('Drive', 'Nicolas Winding Refn', 2011, 8.0, 'Stunt driver gets involved in a criminal underworld.'),
('La La Land', 'Damien Chazelle', 2016, 8.0, 'Romantic musical about aspiring artists in Los Angeles.'),
('The Big Lebowski', 'Joel Coen', 1998, 8.0, 'Laid-back dude becomes entangled in a kidnapping plot.'),
('The Farewell', 'Lulu Wang', 2019, 8.0, 'Family returns to China under the guise of a fake wedding.'),
('The Last Samurai', 'Edward Zwick', 2003, 8.0, 'American military officer embraces Japanese samurai culture.'),
('The Disaster Artist', 'James Franco', 2017, 8.0, 'Behind-the-scenes story of the making of a cult film.'),
('The Straight Story', 'David Lynch', 1999, 8.0, 'Elderly man travels cross-country to reconcile with brother.'),
('Tinker Tailor Soldier Spy', 'Tomas Alfredson', 2011, 8.0, 'Spy thriller about uncovering a Soviet mole in MI6.'),
('The Secret Life of Walter Mitty', 'Ben Stiller', 2013, 8.0, 'Daydreamer embarks on a global adventure to find a photo.'),
('Annihilation', 'Alex Garland', 2018, 8.0, 'Scientists explore a mysterious and dangerous zone.'),
('The Truman Show', 'Peter Weir', 1998, 8.0, 'Man discovers his entire life is a TV show.'),
('The Lovely Bones', 'Peter Jackson', 2009, 8.0, 'Girl watches from heaven as her family copes with her murder.'),
('Good Will Hunting', 'Gus Van Sant', 1997, 8.0, 'Genius janitor confronts his troubled past with therapist.'),
('The Artist', 'Michel Hazanavicius', 2011, 8.0, 'Silent film star struggles with the advent of talkies.'),
('The Maltese Falcon', 'John Huston', 1931, 8.0, 'Private detective gets entangled in a quest for a statue.'),
('A Quiet Place', 'John Krasinski', 2018, 8.0, 'Family must live in silence to avoid monsters.'),
('The Secret Garden', 'Marc Munden', 2020, 8.0, 'Girl discovers a hidden garden on a remote estate.'),
('The Witcher', 'Lauren Schmidt Hissrich', 2019, 8.0, 'Monster hunter navigates a world full of magic and danger.'),
('The Trial of the Chicago 7', 'Aaron Sorkin', 2020, 8.0, 'Activists face trial for protesting the 1968 Democratic Convention.'),
('The Hundred-Foot Journey', 'Lasse Hallström', 2014, 8.0, 'Indian family opens restaurant in a French village, sparking a culinary rivalry.'),
('The Lighthouse', 'Robert Eggers', 2019, 8.0, 'Two lighthouse keepers descend into madness on a remote island.'),
('The Good Place', 'Michael Schur', 2016, 8.0, 'Woman mistakenly sent to heaven tries to become a better person.'),
('The Perks of Being a Wallflower', 'Stephen Chbosky', 2012, 8.0, 'Introverted teen finds friendship and acceptance in high school.'),
('The Grand Seduction', 'Don McKellar', 2013, 8.0, 'Small town tries to lure a doctor to stay by faking a thriving community.'),
('The Lovely Bones', 'Peter Jackson', 2009, 8.0, 'Young girl watches over her family and murderer after being killed.'),
('The King’s Speech', 'Tom Hooper', 2010, 8.0, 'King George VI works to overcome his stammer with the help of a speech therapist.'),
('The Green Mile', 'Frank Darabont', 1999, 8.0, 'Death row officer forms a bond with a prisoner with a mysterious gift.'),
('The Book Thief', 'Brian Percival', 2013, 8.0, 'Young girl finds solace in stealing books during WWII in Nazi Germany.'),
('The Danish Girl', 'Tom Hooper', 2015, 8.0, 'The story of Lili Elbe, one of the first known recipients of sex reassignment surgery.'),
('The Secret Life of Pets', 'Chris Renaud', 2016, 8.0, 'What pets do when their owners are away.'),
('The Maze Runner', 'Wes Ball', 2014, 8.0, 'Teens trapped in a maze must find their way out while facing deadly challenges.'),
('The Curious Case of Benjamin Button', 'David Fincher', 2008, 8.0, 'A man ages backward, experiencing life in reverse.'),
('The Hateful Eight', 'Quentin Tarantino', 2015, 8.0, 'Eight strangers take refuge from a blizzard in a stagecoach lodge.'),
('The Fault in Our Stars', 'Josh Boone', 2014, 8.0, 'Teenagers with cancer meet at a support group and fall in love.'),
('The Social Network', 'David Fincher', 2010, 8.0, 'The story of Facebook’s founding and the ensuing legal battles.'),
('The Martian', 'Ridley Scott', 2015, 8.0, 'Astronaut stranded on Mars struggles to survive and return home.'),
('The Pursuit of Happyness', 'Gabriele Muccino', 2006, 8.0, 'Single father overcomes adversity to pursue his dream of becoming a stockbroker.'),
('The Help', 'Tate Taylor', 2011, 8.0, 'Young writer interviews African-American maids in the 1960s South.'),
('The Blind Side', 'John Lee Hancock', 2009, 8.0, 'Story of Michael Oher, a homeless teen who becomes a football star.'),
('The Devil Wears Prada', 'David Frankel', 2006, 8.0, 'Young woman navigates the demanding world of high fashion under a ruthless boss.'),
('The Vow', 'Michael Sucsy', 2012, 8.0, 'A man works to rekindle his relationship with his wife after she loses her memory.'),
('The Conjuring', 'James Wan', 2013, 8.0, 'Paranormal investigators help a family terrorized by a dark presence in their farmhouse.'),
('The Shining', 'Stanley Kubrick', 1980, 8.0, 'Family caretaker of a secluded hotel slowly descends into madness.'),
('The Walking Dead', 'Frank Darabont', 2010, 8.0, 'Group of survivors navigate a post-apocalyptic world overrun by zombies.'),
('The Hobbit: An Unexpected Journey', 'Peter Jackson', 2012, 8.0, 'Hobbit embarks on a quest to reclaim a lost kingdom.'),
('The Hunger Games', 'Gary Ross', 2012, 8.0, 'Teenagers fight to the death in a dystopian future society.'),
('The Boy in the Striped Pajamas', 'Mark Herman', 2008, 8.0, 'A young boy befriends a Jewish boy in a concentration camp.'),
('The Da Vinci Code', 'Ron Howard', 2006, 8.0, 'A symbologist uncovers a conspiracy while investigating a murder at the Louvre.'),
('The Notebook', 'Nick Cassavetes', 2004, 8.0, 'A love story spanning decades between a poor young man and a wealthy young woman.'),
('The Aviator', 'Martin Scorsese', 2004, 8.0, 'Biopic of Howard Hughes, focusing on his early career and aviation.'),
('The Perks of Being a Wallflower', 'Stephen Chbosky', 2012, 8.0, 'Introverted high school freshman finds a group of friends who understand him.'),
('The Descendants', 'Alexander Payne', 2011, 8.0, 'Hawaiian land baron tries to reconnect with his daughters after his wife’s accident.'),
('The Bourne Identity', 'Doug Liman', 2002, 8.0, 'Amnesiac assassin tries to piece together his past while evading pursuers.'),
('The Conjuring 2', 'James Wan', 2016, 8.0, 'Paranormal investigators help a family haunted by a demonic nun.'),
('The Hangover', 'Todd Phillips', 2009, 8.0, 'Three friends search for their missing friend after a wild bachelor party in Las Vegas.'),
('The Secret Life of Walter Mitty', 'Ben Stiller', 2013, 8.0, 'Daydreamer embarks on a global adventure to find a missing photo.'),
('The Accountant', 'Gavin O’Connor', 2016, 8.0, 'Autistic accountant with lethal skills uncovers a conspiracy.'),
('The Theory of Everything', 'James Marsh', 2014, 8.0, 'Biopic of Stephen Hawking’s life, focusing on his relationship with his first wife.'),
('The Big Short', 'Adam McKay', 2015, 8.0, 'Story of the financial crisis of 2007-2008 through the eyes of investors who bet against the housing market.'),
('The Notebook', 'Nick Cassavetes', 2004, 8.0, 'Romantic drama about a young couple who fall in love during the early years of World War II.'),
('The Fault in Our Stars', 'Josh Boone', 2014, 8.0, 'Two teenage cancer patients meet at a support group and fall in love.'),
('The Sixth Sense', 'M. Night Shyamalan', 1999, 8.0, 'Child psychologist treats a young boy who claims to see dead people.'),
('The Intouchables', 'Olivier Nakache', 2011, 8.0, 'A quadriplegic aristocrat hires a young man from the projects to be his caregiver.'),
('The Girl with the Dragon Tattoo', 'David Fincher', 2011, 8.0, 'Journalist and hacker investigate a wealthy family’s dark secrets.'),
('The Dark Knight', 'Christopher Nolan', 2008, 8.0, 'Batman faces off against the Joker, a criminal mastermind wreaking havoc on Gotham City.');


